name: Build AIRI Android

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # 1) Android SDK спершу
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 2) Точно JDK 21
      - name: Use Java 21 (Temurin)
        id: java21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Java
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # 3) Потрібні платформи/білд-тули
      - name: Install Android build tools
        run: |
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" || true

      # 4) Діагностика структури (не обов'язково, але корисно)
      - name: Show repo tree (top)
        run: |
          pwd
          ls -la
          echo "== apps =="
          ls -la apps || true
          echo "== apps/stage-web =="
          ls -la apps/stage-web || true

      # 5) Веб-залежності + збірка
      - name: Install deps & build web
        working-directory: apps/stage-web
        run: |
          pnpm install
          pnpm build

      # 6) Capacitor пакети
      - name: Install Capacitor deps
        working-directory: apps/stage-web
        run: |
          pnpm add -D @capacitor/core @capacitor/cli @capacitor/android

      # 7) Додаємо Android-платформу
      - name: Add Android platform
        working-directory: apps/stage-web
        run: pnpm exec cap add android || true

      # 8) Синк
      - name: Sync Capacitor → Android
        working-directory: apps/stage-web
        run: pnpm exec cap sync android

      # 9) Скажемо Gradle, де взяти JDK 21
      - name: Force Gradle to use Java 21
        working-directory: apps/stage-web/android
        run: |
          echo "org.gradle.java.home=${{ steps.java21.outputs.path }}" >> gradle.properties
          tail -n +1 gradle.properties

      # 10) Права на gradlew
      - name: Ensure gradlew is executable
        working-directory: apps/stage-web/android
        run: chmod +x ./gradlew || true

      # 11) Збірка APK (передаємо JAVA_HOME прямо в кроці)
      - name: Assemble Debug APK
        working-directory: apps/stage-web/android
        env:
          JAVA_HOME: ${{ steps.java21.outputs.path }}
        run: ./gradlew --no-daemon assembleDebug

      # 12) Артефакт
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: apps/stage-web/android/app/build/outputs/apk/debug/app-debug.apk
