name: Build AIRI Android

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # 1) Android SDK ставимо раніше
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 2) Потім ставимо саме JDK 21 і зберігаємо шлях у GITHUB_ENV
      - name: Use Java 21 (Temurin)
        id: java21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Pin JAVA_HOME to 21
        run: |
          echo "JAVA_HOME=${{ steps.java21.outputs.path }}" >> $GITHUB_ENV
          echo "JAVA_TOOL_OPTIONS=--release 21" >> $GITHUB_ENV
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # Про запас: потрібні платформи/білд-тули
      - name: Install Android build tools
        run: |
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" || true

      # Діагностика структури
      - name: Show repo tree (top)
        run: |
          pwd
          ls -la
          echo "== apps =="
          ls -la apps || true
          echo "== apps/stage-web =="
          ls -la apps/stage-web || true

      # 3) Веб-залежності + збірка веб-частини
      - name: Install deps & build web
        working-directory: apps/stage-web
        run: |
          pnpm install
          pnpm build

      # 4) Ставимо пакети Capacitor
      - name: Install Capacitor deps
        working-directory: apps/stage-web
        run: |
          pnpm add -D @capacitor/core @capacitor/cli @capacitor/android

      # 5) Додаємо Android-платформу і синк через pnpm exec
      - name: Add Android platform
        working-directory: apps/stage-web
        run: pnpm exec cap add android || true

      - name: Sync Capacitor → Android
        working-directory: apps/stage-web
        run: pnpm exec cap sync android

      # 6) Примусово кажемо Gradle використовувати саме JDK 21
      - name: Force Gradle to use Java 21
        working-directory: apps/stage-web/android
        run: |
          echo "org.gradle.java.home=${{ steps.java21.outputs.path }}" >> gradle.properties
          tail -n +1 gradle.properties

      # 7) Права на gradlew
      - name: Ensure gradlew is executable
        working-directory: apps/stage-web/android
        run: chmod +x ./gradlew || true

      # 8) Збірка APK з явною передачею JDK 21
      - name: Assemble Debug APK
        working-directory: apps/stage-web/android
        run: ./gradlew --no-daemon -Dorg.gradle.java.home=${{ steps.java21.outputs.path }} assembleDebug

      # 9) Артефакт
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: apps/stage-web/android/app/build/outputs/apk/debug/app-debug.apk
