name: Build AIRI Android

on:
  workflow_dispatch: {}   # тільки ручний запуск

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # Спочатку Android SDK (деякі екшени люблять підтягнути свій JDK)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ТЕПЕР ставимо Java 21 (останнім, щоб нічого не переїхало на 17)
      - name: Use Java 21 (Temurin)
        id: java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Перевіримо що справді 21
      - name: Verify Java
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # Про запас: поставимо потрібні платформи/білд-тули
      - name: Install Android build tools
        run: |
          yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" || true

      # Діагностика структури репо
      - name: Show repo tree (top)
        run: |
          pwd
          ls -la
          echo "== apps =="
          ls -la apps || true
          echo "== apps/stage-web =="
          ls -la apps/stage-web || true

      # 1) Веб-залежності + збірка веб-частини
      - name: Install deps & build web
        working-directory: apps/stage-web
        run: |
          pnpm install
          pnpm build

      # 2) Ставимо пакети Capacitor
      - name: Install Capacitor deps
        working-directory: apps/stage-web
        run: |
          pnpm add -D @capacitor/core @capacitor/cli @capacitor/android

      # 3) Додаємо Android-платформу
      - name: Add Android platform
        working-directory: apps/stage-web
        run: pnpm exec cap add android || true

      # 4) Синхронізуємо
      - name: Sync Capacitor → Android
        working-directory: apps/stage-web
        run: pnpm exec cap sync android

      # 5) Примусово вказуємо Gradle, яку Java брати
      - name: Force Gradle to use Java 21
        working-directory: apps/stage-web/android
        run: |
          echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
          cat gradle.properties | tail -n +1

      # 6) Права на gradlew
      - name: Ensure gradlew is executable
        working-directory: apps/stage-web/android
        run: chmod +x ./gradlew || true

      # 7) Збірка APK
      - name: Assemble Debug APK
        working-directory: apps/stage-web/android
        run: ./gradlew --no-daemon assembleDebug

      # 8) Артефакт
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: apps/stage-web/android/app/build/outputs/apk/debug/app-debug.apk
