name: Build AIRI Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # 1) Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools-version: 35.0.0

      # 2) JDK 21
      - name: Use Java 21 (Temurin)
        id: java21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Java
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # 3) Встановлення залежностей та збірка вебу
      - name: Install deps & build web
        working-directory: apps/stage-web
        run: |
          pnpm install
          pnpm build

      # 4) Встановлення Capacitor залежностей
      - name: Install Capacitor deps
        working-directory: apps/stage-web
        run: |
          pnpm add -D @capacitor/core @capacitor/cli @capacitor/android

      # 5) Додаємо Android-платформу (якщо ще нема)
      - name: Add Android platform
        working-directory: apps/stage-web
        run: pnpm exec cap add android || true

      # 6) Синк
      - name: Sync Capacitor → Android
        working-directory: apps/stage-web
        run: pnpm exec cap sync android

      # 7) Автоправка AndroidManifest.xml
      - name: Fix AndroidManifest (remove package attr)
        run: |
          sed -i 's/\s*package="[^"]*"//g' apps/stage-web/android/app/src/main/AndroidManifest.xml
          echo "✅ Manifest cleaned:"
          head -n 5 apps/stage-web/android/app/src/main/AndroidManifest.xml

      # 8) Перевірка, що package дійсно прибрано
      - name: Verify Manifest
        run: |
          if grep -n 'package="' apps/stage-web/android/app/src/main/AndroidManifest.xml; then
            echo "❌ Manifest still contains package attr"
            exit 1
          else
            echo "✅ No package attr found, safe to build"
          fi

      # 9) Права на gradlew
      - name: Ensure gradlew is executable
        working-directory: apps/stage-web/android
        run: chmod +x ./gradlew || true

      # 10) Збірка APK
      - name: Assemble Debug APK
        working-directory: apps/stage-web/android
        env:
          JAVA_HOME: ${{ steps.java21.outputs.path }}
        run: ./gradlew --no-daemon assembleDebug

      # 11) Завантаження артефакту
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: apps/stage-web/android/app/build/outputs/apk/debug/app-debug.apk